apiVersion: v1
kind: Service
metadata:
  name:  oluwa-rtp-service
  namespace: oluwa
spec:
  type: NodePort
  selector:
    app: oluwa-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000